package rules

import com.project.Player;
import com.project.Action;
import com.project.Phase;
import com.project.Table;
import com.project.cards.Card;
import com.project.cards.kingdoms.*;
import com.project.cards.treasures.*;
import com.project.cards.victories.*;
import com.project.cards.curses.*;
import java.util.*;

//List of trash cards
global List<Card> trashPile;
//Random logic
global Random gameLogic;
//Actual player if used as global variable is read only
//global Player actualPlayer;
//Table
global Table table;
//Players
global List<Player> players;

/*
 _______  __   __  __    _  _______  _______  ___   _______  __    _  _______ 
|       ||  | |  ||  |  | ||       ||       ||   | |       ||  |  | ||       |
|    ___||  | |  ||   |_| ||       ||_     _||   | |   _   ||   |_| ||  _____|
|   |___ |  |_|  ||       ||       |  |   |  |   | |  | |  ||       || |_____ 
|    ___||       ||  _    ||      _|  |   |  |   | |  |_|  ||  _    ||_____  |
|   |    |       || | |   ||     |_   |   |  |   | |       || | |   | _____| |
|___|    |_______||_|  |__||_______|  |___|  |___| |_______||_|  |__||_______|
*/
//A Player *p* draw *amound* cards from the deck
function void draw(Player p, int amount) {
	if(p.getDeck().size() < amount) {
		int deckSize = p.getDeck().size();
		for(int h = 0; h < deckSize; h++)
			p.addToHand(p.getDeck().remove(0));
		// the remaining cards are drawn after shuffling together deck and discard
		Collections.shuffle(p.getDiscard());
		p.getDeck().addAll(p.getDiscard());
		p.getDiscard().clear();
		for(int j = 0; j < amount-deckSize; j++) 
			p.addToHand(p.getDeck().remove(0));
	} else 
		for(int j = 0; j < 5; j++) 
		p.addToHand(p.getDeck().remove(0));
	System.out.println(p.getUsername() + " drew " + amount + " cards.");
}

//A player *p* obtain *amount* virtual coins
function void coin(Player p, int amount) {
	p.setVirtualCoins(p.getVirtualCoins()+amount);
	System.out.println(p.getUsername() + " obtained " + amount + " coins and has a total of:" + p.getVirtualCoins());
}

//A player *p* buy a card *c*
function void buy(Player p, Card c) {
	p.getDiscard().add(c);
	System.out.println(p.getUsername() + " bought " + c.getName());
}

function void gainOntoDeck(Table table, Player p, Card c) {
	if(table.checkDeckSize(c) > 0) {
		p.getDeck().add(0,c);
		table.decreaseDeckSize(c);
	}
}

function void gainIntoDiscardPile(Table table, Player p, Card c) {
	if(table.checkDeckSize(c) > 0) {
		p.getDiscard().add(c);
		table.decreaseDeckSize(c);
	}
}

//A player *p* is cursed!
function void beCursed(Player p) {
	p.getDiscard().add(new com.project.cards.curses.Curse());
	System.out.println(p.getUsername() + " obtained a Curse");
}

//A player *p* discard *amount* card (in random way)
function void discard(Player p, int amount) {
	Random r = new Random();
	for(int i = 0; i < amount; i++) {
		p.getHand().remove(r.nextInt(p.getHand().size()));
	}
	System.out.println(p.getUsername() + " discarded " + amount + " cards.");
}

//A player *p* add from discard pile *amount* card in random way
function void addFromDiscardPile(Player p, int amount) {
	Random r = new Random();
	for(int i = 0; i < amount; i++) {
		Card c = p.getDiscard().remove(r.nextInt(p.getDiscard().size()));
		p.getHand().add(c);
		System.out.println(p.getUsername() + " added " + c.getName() + " from his/her discard pile.");
	}
	System.out.println(p.getUsername() + " added a total of " + amount + " cards from his/her discard pile.");
}


function void addActions(Player p, int amount) {
	p.setActions(p.getActions()+amount);
	System.out.println(p.getUsername() + " can do " + amount + " more actions.");
}


function void addPurchase(Player p, int amount) {
	p.setPurchases(p.getPurchases()+amount);
	System.out.println(p.getUsername() + " can purchase " + amount + " more cards.");
}

/*
function void trash(Player p, Card c) {
	p.getHand().remove(index);
	trashPile.add(c);
}
*/


rule "Switch Turn"
	when
		$action : Phase( this == Phase.ENDTURN )
		actualPlayer : Player(  )
		not Action(  )
	then
		System.out.println(actualPlayer.getUsername() + " ENDED its turn");
		int indexActualPlayer = players.indexOf(actualPlayer);
		//If the actual player is the last player of the list
		if(indexActualPlayer == players.size() - 1){
			actualPlayer = (Player)players.get(0);
		} else {
			actualPlayer = (Player)players.get(indexActualPlayer+1);
		}
		System.out.println("________________________________________________");
		System.out.println("Now it's the turn of " + actualPlayer.getUsername());
		//Reset the number of Actions and Purchases to the default value (1)
		actualPlayer.setActions(1);
		actualPlayer.setPurchases(1);
		
		retract($action);
		insert(Phase.ACTION);
		retract(actualPlayer);
		insert(actualPlayer);
end




rule "Action Phase Rule"
	no-loop
	//According to us we must give an order:
	//	1 - player choose the card from the hand
	//	2 - it Plays the card
	//	3 - Goto 1 and repeat until player has available actions
	salience 10
	when
		$phase : Phase( this == Phase.ACTION )
		actualPlayer : Player(  )
		not Action(  )
	then
		System.out.println(actualPlayer.getUsername() + " entered in ACTION phase rule");
		if(actualPlayer.getActions() > 0) {
			Card kingdomCardToPlay = actualPlayer.getPlayableKingdomCardFromHand();
			if(kingdomCardToPlay != null)
				System.out.println("Card chosen, card is: " + kingdomCardToPlay);
			else
				System.out.println(actualPlayer.getUsername() + " has no Kingdom cards in hand");
			if(kingdomCardToPlay != null) {
				insert(Action.USE);
				insert(kingdomCardToPlay);
				actualPlayer.decreaseActions();
				System.out.println(actualPlayer.getUsername() + " played " + kingdomCardToPlay.getName());
			} else {
				System.out.println(actualPlayer.getUsername() + " skipped action phase");
				actualPlayer.setActions(0);
				retract($phase);
				insert(Phase.PURCHASE);
			}
		} else {
			retract($phase);
			insert(Phase.PURCHASE);
		}
end


/*
 _______  ___      _______  __   __                                                
|       ||   |    |   _   ||  | |  |                                               
|    _  ||   |    |  |_|  ||  |_|  |                                               
|   |_| ||   |    |       ||       |                                               
|    ___||   |___ |       ||_     _|                                               
|   |    |       ||   _   |  |   |                                                 
|___|    |_______||__| |__|  |___|                                                 
 _______  ______    _______  _______  _______  __   __  ______    _______  _______ 
|       ||    _ |  |       ||   _   ||       ||  | |  ||    _ |  |       ||       |
|_     _||   | ||  |    ___||  |_|  ||  _____||  | |  ||   | ||  |    ___||  _____|
  |   |  |   |_||_ |   |___ |       || |_____ |  |_|  ||   |_||_ |   |___ | |_____ 
  |   |  |    __  ||    ___||       ||_____  ||       ||    __  ||    ___||_____  |
  |   |  |   |  | ||   |___ |   _   | _____| ||       ||   |  | ||   |___  _____| |
  |___|  |___|  |_||_______||__| |__||_______||_______||___|  |_||_______||_______|
*/

/*
rule "Play Treasures card"
	when
		$player : Player( $username : username )
		$card : Treasure( $amount : value )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		coin($player,$amount);
		retract($player)
		retract($card)
		retract($action)
end
*/


/*
 _______  __   __  __   __                                                  
|  _    ||  | |  ||  | |  |                                                 
| |_|   ||  | |  ||  |_|  |                                                 
|       ||  |_|  ||       |                                                 
|  _   | |       ||_     _|                                                 
| |_|   ||       |  |   |                                                   
|_______||_______|  |___|                                                   
 __   __  ___   _______  _______  _______  ______    ___   _______  _______ 
|  | |  ||   | |       ||       ||       ||    _ |  |   | |       ||       |
|  |_|  ||   | |       ||_     _||   _   ||   | ||  |   | |    ___||  _____|
|       ||   | |       |  |   |  |  | |  ||   |_||_ |   | |   |___ | |_____ 
|       ||   | |      _|  |   |  |  |_|  ||    __  ||   | |    ___||_____  |
 |     | |   | |     |_   |   |  |       ||   |  | ||   | |   |___  _____| |
  |___|  |___| |_______|  |___|  |_______||___|  |_||___| |_______||_______|                                                                                               
*/
/*
rule "Buy Victories card"
	when
		$player : Player( $username : username )
		$card : Victory(  )
		$action : Action( this == Action.BUY )
	then
		buy($player,$card);
		retract($player)
		retract($card)
		retract($action)
end
*/

rule "Buy a general card"
	when
		$phase : Phase( this == Phase.PURCHASE )
		actualPlayer : Player(  )
		$action : Action( this == Action.BUY )
		$card : Card(  )
	then
		buy(actualPlayer,$card);
		retract($action);
		retract($card);
end



rule "Purchase Phase rule"
	salience 15
	when 
		$phase : Phase( this == Phase.PURCHASE )
		actualPlayer : Player(  )
		not Action(  )
	then
		System.out.println(actualPlayer.getUsername() + " passed to PURCHASE phase");
		Card cardToBuy = null;
		if(actualPlayer.getPurchases() > 0) {
			actualPlayer.playAllTreasureCardsInHand();
			//Choose a card to buy randomly from the 7 data structures holding decks in table
			List<Card> ca = table.getAllCardsThatCanBeBoughtWithAmountOfCoins(actualPlayer.getVirtualCoins());
			int randomInt = gameLogic.nextInt(ca.size());
			cardToBuy = ca.get(randomInt);
			System.out.println("Chosen card: " + cardToBuy);
			//If I choose a card
			if(cardToBuy != null){
				//I remove the virtual coins of the card
				actualPlayer.decreaseVirtualCoins(cardToBuy.getCost());
				actualPlayer.decreasePurchases();
				table.decreaseDeckSize(cardToBuy);
				insert(Action.BUY);
				insert(cardToBuy);
					
				
			}
		} else {
			retract($phase);
			insert(Phase.CLEANUP);
		}
end

rule "Cleanup phase rule"
	when
		$phase : Phase( this == Phase.CLEANUP )
		actualPlayer : Player(  )
		not Action(  )
	then
		System.out.println(actualPlayer.getUsername() + " is now on CLEANUP phase");
		actualPlayer.getDiscard().addAll(actualPlayer.getHand());
		System.out.println(actualPlayer.getUsername() + " discarded the hand");
		actualPlayer.getHand().clear();
		draw(actualPlayer,5);
		//Check if end game conditions are satisifed at the end of each turn
		table.checkEndGame();
		System.out.println("End game conditions checked");
		retract($phase);
		insert(Phase.ENDTURN);
		
end



/*
 _______  ___      _______  __   __                         
|       ||   |    |   _   ||  | |  |                        
|    _  ||   |    |  |_|  ||  |_|  |                        
|   |_| ||   |    |       ||       |                        
|    ___||   |___ |       ||_     _|                        
|   |    |       ||   _   |  |   |                          
|___|    |_______||__| |__|  |___|                          
 ___   _  ___   __    _  _______  ______   _______  __   __ 
|   | | ||   | |  |  | ||       ||      | |       ||  |_|  |
|   |_| ||   | |   |_| ||    ___||  _    ||   _   ||       |
|      _||   | |       ||   | __ | | |   ||  | |  ||       |
|     |_ |   | |  _    ||   ||  || |_|   ||  |_|  ||       |
|    _  ||   | | | |   ||   |_| ||       ||       || ||_|| |
|___| |_||___| |_|  |__||_______||______| |_______||_|   |_|
*/

/*
rule "Play Witch card"
	when
		$player : Player( $username : username )
		$opponents : List(  )
		$card : Witch(  )
		$action : Action( this == Action.USE )
	then
		buy($player,$card);
		retract($player)
		retract($card)
		retract($action)
end
*/


/*
--------------------------------------
		PLAY AND BUY KINGDOMS
--------------------------------------
*/

//Gain a card to your hand costing up 5 coins
//Put a card from your hand onto your deck
rule "Play Artisan card"
	when
		$player : Player( $username : username )
		$table : Table(  )
		$card : Artisan(  )
		$action : Action( this == Action.USE )
	then
		Card cardToGain = null;
		System.out.println($username+" used "+$card.getName()+".");
		// gain a card to your hand costing up to 5 either from Treasure, Victory or Kingdom decks
		List<Card> ca = table.getAllCardsThatCanBeGainedUpToAmount(5);
		int randomInt = gameLogic.nextInt(ca.size());
		cardToGain = ca.get(randomInt);
		$player.getHand().add(cardToGain);
		table.decreaseDeckSize(cardToGain);
		// put a card from your hand onto your deck
		Collections.shuffle($player.getHand());
		Card cardToPutInDeck = null;
		randomInt = gameLogic.nextInt($player.getHand().size());
		cardToPutInDeck = $player.getHand().get(randomInt);
		//onto your deck means at the top of the deck, since we use remove(0) to draw, position 0 is the top
		$player.getDeck().add(0,cardToPutInDeck);
		$player.getHand().remove(randomInt);
		
		retract($card)
		retract($action)
end

//Reveal cards from your deck until you reveal 2 treasure cards.
//Put those Treasure card into your hand
//and discard the other revealed cards
rule "Play Adventurer card"
	when
		$player : Player( $username : username )
		$card : Adventurer(  )
		$action : Action( this == Action.USE )
		$phase : Phase( this == Phase.ACTION )
	then
		System.out.println($username+" used "+$card.getName()+".");
		// reveal cards from your deck until you reveal 2 Treasure cards
		// TODO: Draw from hand and print the log because revealed, until you have seen 2 treasure cards,
		// while you draw, discard the cards if they are not treasure cards
		// instead if they are treasure cards put them in the hand
		// put those Treasure cards into your hand and discard the other revealed cards
		Iterator<Card> it = $player.getDeck().iterator();
		while(it.hasNext()) {
			Card c = it.next();
			System.out.println($player.getUsername() + " reveals " + c.getName() + " from his deck");
			if(c instanceof Treasure) {
				//If it is a treasure add it to the hand
				$player.getHand().add(c);
				it.remove();
			} else {
				//Instead discard it
				$player.getDiscard().add(c);
				it.remove();
			}
		}
		retract($card)
		retract($action)
end

//Gain a Gold.
//Each other player reveals the top 2 cards of their deck,
//trashes a revealed Treasure other than Copper
//and Discards the rest
rule "Play Bandit card"
	when
		$player : Player( $username : username )
		$opponents : List(  ) from collect ( Player( this != $player ) from players )
		$card : Bandit(  )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		
		
		//If an opponent has a reaction card it is not affected by the attack
		for(Iterator<Player> it = $opponents.iterator(); it.hasNext();) {
			Player opp = it.next();
			for(Card c : opp.getHand()) {
				if(c instanceof Kingdom && c.getSubtype().equals("Reaction")) {
					System.out.println(opp.getUsername() + " reveals " + c.getName() + " and is not affected by Bandit");
					it.remove();
					break;
				}
			}
		}
		
		// gain a Gold card
		gainIntoDiscardPile(table,$player,new Gold());
		// each other player reveals the tops 2 cards of their deck
		// he has to trash the revealed Tresure other than Copper 
		// he discards the rest.
		for(Player opp : ((List<Player>)$opponents)) {
			int i = 0;
			Iterator<Card> it = opp.getDeck().iterator();
			while(i < 2 && it.hasNext()) {
				Card c = it.next();
				System.out.println(opp.getUsername() + " reveals " + c.getName());
				if(c instanceof Treasure && !(c instanceof Copper)) {
					trashPile.add(c);
					it.remove();
					System.out.println(opp.getUsername() + " trashes " + c.getName());
				} else {
					$player.getDiscard().add(c);
					it.remove();
					System.out.println(opp.getUsername() + " discards " + c.getName());
				}
				i++;
			}
		}
		
		
		retract($opponents)
		retract($card)
		retract($action)
end


//Gain a Silver onto your deck.
//Each other player reveals a Victory card
//from their hand and puts it onto their 
//deck (or reveals a hand with no victory cards).
rule "Play Bureaucrat card"
	when
		$player : Player( $username : username )
		$opponents : List(  ) from collect ( Player( this != $player ) from players )
		$card : Bureaucrat()
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		//It is a gainer which lets you gain Silver cards without buying them, 
		//and puts them on top of your deck so you can use them next turn; 
		//it also slows down your opponents by making them put Victory cards from 
		//their hands back on top of their deck.
		//$player.addToDeck();
		//	p.getHand().add(p.getDeck().remove(0));
		//for(Player p : ListaGiocatori){
		//while(p.
		//}
		// gain a silver onto your deck
		gainOntoDeck(table,$player,new Silver());
		
		for(Player opp : ((List<Player>)$opponents)) {
			int cardToPutOntoDeck = 0;
			if(opp.getHand().indexOf(new Estate()) > 0) {
				cardToPutOntoDeck = opp.getHand().indexOf(new Estate());
				System.out.println(opp.getUsername() + " reveals " + new Estate().getName());
				
			}
			
		}
		retract($card)
		retract($action)
end



// + 1 Action
// Discard any number of card
// +1 Card per card discarded
rule "Play Cellar card"
	when
		$player : Player( $username : username )
		$card : Cellar( )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		//Choose a number between 0 and #CardInHand
		int randomNumberOfCard = gameLogic.nextInt($player.getHand().size());
		//Discard #randomNumberOfCard
		discard($player,randomNumberOfCard);
		//Draw #randomNumberOfCard
		draw($player,randomNumberOfCard);
		
		retract($player)
		retract($card)
		retract($action)
end

// +2 Coins
// You may immediately put your deck into your discard pile
rule "Play Chancellor card"
	when
		$player : Player( $username : username )
		$card : Chancellor(  )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		coin($player,2);
		// you have to put your deck onto your discard pile
		retract($player)
		retract($card)
		retract($action)
end


// Trash up to 4 cards from your hand
rule "Play Chapel card"
	when
		$player : Player( $username : username )
		$card : Chapel( $amount : amount )
		$action : Action( this == Action.USE )
	then
		
		System.out.println($username+" used "+$card.getName()+".");
		// trash cards here
		retract($player)
		retract($card)
		retract($action)
end

// +4 cards
// +1 buy
// each other player draws a card
rule "Play Council room card"
	when
		$player : Player( $username : username )
		$card : Councilroom(  )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		draw($player,4);
		addPurchase($player,1);
		// each other player draws a card
		retract($player)
		retract($card)
		retract($action)
end

//Trash this card.
//Gain a card costing up to 5 coins
rule "Play Feast card"
	when
		$player : Player( $username : username )
		$card : Feast(  )
		$action : Action( this == Action.USE )
	then
		// trash this card 
		// gain a card costing up to 5 
		System.out.println($username+" used "+$card.getName()+".");
		addActions($player,2);
		addPurchase($player,1);
		coin($player,2);
		retract($player)
		retract($card)
		retract($action)
end

// +2 actions
// +1 buy
// +2 coins
rule "Play Festival card"
	when
		$player : Player( $username : username )
		$card : Festival(  )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		draw($player,1);
		addPurchase($player,1);
		coin($player,2);
		retract($player)
		retract($card)
		retract($action)
end

// Worth 1 victory per 10 cards you have
// (round down)
rule "Play Gardens card"
	when
		$player : Player( $username : username )
		$card : Gardens(  )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		retract($player)
		retract($card)
		retract($action)
end

/*
rule "Play Harbinger card"
	when
		$player : Player( $username : username )
		$card : Harbinger(  )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used Harbinger.");
		draw($player,1);
		addActions($player,1);
		if(gameLogic.nextBoolean()) {
			addFromDiscardPile($player,1);
		}
		retract($player)
		retract($card)
		retract($action)
end
*/

// +1 card
// +1 action
// Look through your discard pile.
// You may put a card from it onto your deck.
rule "Play Harbinger card"
	when
		$player : Player( $username : username )
		$card : Harbinger(  )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		draw($player,1);
		addActions($player,1);
		// look through your discrda pile 
		// you may put a card from it into your deck
		retract($player)
		retract($card)
		retract($action)
end

// +2 cards
// +1 action
rule "Play Laboratory card"
	when
		$player : Player( $username : username )
		$card : Laboratory(  )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		draw($player,2);
		addActions($player,1);
		retract($player)
		retract($card)
		retract($action)
end

//Draw until you have 7 cards in hand, skipping
// any Action cards you choose to; set those aside
// discarding them afterwards
rule "Play Library card"
	when
		$player : Player( $username : username )
		$card : Library(  )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		// draw until you have 7 cards in hand,
		int lastHandSize = $player.getHand().size();
		System.out.println($username+" used "+$card.getName()+".");
		draw($player,Math.max(7,Math.abs(7-$player.getHand().size())));
		// skipping any Action cards you choose to
		// set them aside and discard them afterwards
		//draw($player,?);
		retract($player)
		retract($card)
		retract($action)
end


// +1 Card
// +1 Action
// +1 Buy
// +1 Coin
rule "Play Market card"
	when
		$player : Player( $username : username )
		$card : Market(  )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		draw($player,1);
		addActions($player,1);
		addPurchase($player,1);
		coin($player,1);
		retract($player)
		retract($card)
		retract($action)
end


//You may trash a Treasure from your hand.
//Gain a Treasure to your hand costing up to 3 coins
//more than it
rule "Play Mine card"
	when
		$player : Player( $username : username )
		$card : Mine(  )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		
		//Selection of the Treasure
		Treasure selectedTreasuresToTrash = null;
		for(Card card : $player.getHand()){
			if(card instanceof Treasure){
				selectedTreasuresToTrash = (Treasure) card;
				break;
			}
		}
		
		//If I have a treasure
		if(selectedTreasuresToTrash != null)
		{
			//trash the selectedTreasures
			trashPile.add(selectedTreasuresToTrash);
			$player.getHand().remove(selectedTreasuresToTrash);
						
			//If there are Gold card in the gold deck and the selectedTreasuresToTrash 
			// is not a copper I can gain a Gold deck
			if(	!table.getGoldDeck().isEmpty() && 
				!(selectedTreasuresToTrash instanceof Copper)){
				$player.getHand().add(table.getGoldDeck().remove(0));
			} else {
				//Try to gain a silver else a cooper
				try{
					$player.getHand().add(table.getSilverDeck().remove(0));
				}catch(Exception e){
					$player.getHand().add(table.getCopperDeck().remove(0));
				}
			}
		}else{
			System.out.println($username+" has not treasure in his/her hand.");
		}
		
		retract($player)
		retract($card)
		retract($action)
end

//+1 card
//+1 action
//the first time you play a silver this turn
//+1 coin
rule "Play Merchant card"
	when
		$player : Player( $username : username )
		$card : Merchant(  )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		draw($player,1);
		addActions($player,1);
		// the first time you play a Silver this turn 
		// coin($player,1);
		retract($player)
		
		retract($card)
		retract($action)
end


// +2 Coins
// Each other player discards down to 3 cards in his hand

//FAQ
//Players with 3 or fewer cards in hand do not discard any cards.
//Players with more cards discard until they only have 3.
rule "Play Militia card"
	when
		$player : Player( $username : username )
		$card : Market(  )
		$action : Action( this == Action.USE )
	then
		coin($player,2);
		for(Object player : players){
			Player p = (Player)player;
			if(!p.equals($player)){
				if(p.getHand().size()>=3){
					discard(p, 3);
				}
			}
		}
		retract($player)
		retract($card)
		retract($action)
end

//Gain a card costing up to 4

//FAQ
//The card you gain comes from the Supply and is put into your discard pile.
rule "Play Workshop card"
	when
		$player : Player( $username : username )
		$card : Workshop(  )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		
		//Get all gainable card
		List<Card> listOfGainableCard = table.getAllCardsThatCanBeGainedUpToAmount(4);
		//Choose the card to gain between listOfGainableCard
		Card selectedCardToGain = listOfGainableCard.get(gameLogic.nextInt(listOfGainableCard.size()));
		//Add to hand the selected card
		$player.getHand().add(selectedCardToGain);
		//Remove to deck the selected card
		table.decreaseDeckSize(selectedCardToGain);
		retract($player)
		retract($card)
		retract($action)
end

// + 2 Cards
// When another player plays an Attack card,
// you may first reveal this from your hand, 
// to be unaffected by it
rule "Play Moat card"
	when
		$player : Player( $username : username )
		$card : Moat(  )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		draw($player,2);
		// when amother player plays an Attack card, 
		// you can reveal it from your hand and 
		// Attack card doesn't affect you
		retract($player)
		retract($card)
		retract($action)
end


//You may trash a Copper from your hand for +3 coins
rule "Play Moneylender card"
	when
		$player : Player( $username : username )
		$card : Moneylender(  )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		// you may trash a Copper from your hand for 3 
		retract($player)
		retract($card)
		retract($action)
end


// +1 Card
// +1 Action
// +1 coin
// Discard a card per empty supply pile
rule "Play Poacher card"
	when
		$player : Player( $username : username )
		$card : Poacher(  )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		draw($player,1);
		addActions($player,1);
		coin($player,1);
		// discard a card per empty supply card
		retract($player)
		retract($card)
		retract($action)
end

//Trash a card from your hand.
//Gain a card costing up to 2 coins
//more than it
rule "Play Remodel card"
	when
		$player : Player( $username : username )
		$card : Chapel(  )
		$action : Action( this == Action.BUY )
	then
		
		if($player.getHand().size() !=0) {
			int randomNumberOfCard = gameLogic.nextInt($player.getHand().size());
			//Select a card to trash
			Card selectedCardToTrash = $player.getHand().remove(randomNumberOfCard);
			//Get all gainable card
			List<Card> listOfGainableCard = table.getAllCardsThatCanBeGainedUpToAmount(selectedCardToTrash.getCost()+2);
			//Choose the card to gain between listOfGainableCard
			Card selectedCardToGain = listOfGainableCard.get(gameLogic.nextInt(listOfGainableCard.size()));
			//Add to hand the selected card
			$player.getHand().add(selectedCardToGain);
			//Remove to deck the selected card
			table.decreaseDeckSize(selectedCardToGain);
		} else {
			System.out.println($username+" has not any card in his/her hand.");
		}
		
		retract($player)
		retract($card)
		retract($action)
end

//+1 Card
//+1 Action
//Look at the top 2 cards of your deck.
//Trash and/or discard any number of them.
//Put the rest back on the top in any order
rule "Play Sentry card"
	when
		$player : Player( $username : username )
		$card : Sentry(  )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		draw($player,1);
		addActions($player,1);
		// look at the top 2 card of your deck 
		// trash and/ot discard any number of them
		// put the rest back on top in any order
		retract($player)
		retract($card)
		retract($action)
end


// +3 Cards
rule "Play Smithy card"
	when
		$player : Player( $username : username )
		$card : Smithy(  )
		// I need the action to understand what the player will do with that card
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		draw($player,3);
		retract($player)
		retract($card)
		retract($action)
end


//+1 card
//+1 action
//Each player (including you) reveals the top
//card of his deck and either discards it or puts it back, your choice
rule "Play Spy card"
	when
		$player : Player( $username : username )
		$card : Spy(  )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		draw($player,1);
		addActions($player,1);
		// tutti i giocatori rivelare una carta dal proprio deck 
		// possono decidere se scartarla o rimetterla al proprio posto
		retract($player)
		retract($card)
		retract($action)
end

//Each other player reveals the top 2 card of his deck.
//If they revealed any treasure card, they trash one
//of them that you choose.
//You may gain any of all of thes trashed card.
//They discard the orger revealed cards
rule "Play Thief card"
	when
		$player : Player( $username : username )
		$card : Thief(  )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		// each other player reveals the top 2 cards of his deck
		// if they revelead any treasure coards 
		// they trash one of them that you choose
		// you may gain any or all these thrashed cards
		// they discard the other revealed cards
		retract($player)
		retract($card)
		retract($action)
end

//You may play and Action card from 
//your hand twice
rule "Play Throne room card"
	when
		$player : Player( $username : username )
		$card : Throneroom(  )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		// you may play an Action card from your hand twice
		retract($player)
		retract($card)
		retract($action)
end


// +2 coins
// Discard the top card of your deck.
//If it's an Action card, you may play it
rule "Play Vassal card"
	when
		$player : Player( $username : username )
		$card : Vassal(  )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		coin($player,2);
		// discard the top card of your deck
		// if it's anAction card,
		// you may play it
		retract($player)
		retract($card)
		retract($action)
end


// +1 card
// +2 actions
rule "Play Village card"
	when
		$player : Player( $username : username )
		$card : Village(  )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		draw($player,1);
		addActions($player,2);
		retract($player)
		retract($card)
		retract($action)
end

// +2 cards
// Each other player gains a Curse
rule "Play Witch card"
	when
		$player : Player( $username : username )
		$card : Witch(  )
		$action : Action( this == Action.USE )
	then
		System.out.println($username+" used "+$card.getName()+".");
		draw($player,2);
		// each other player gains a curse
		retract($player)
		retract($card)
		retract($action)
end


// +1 buy
// +2 coins
rule "Play Woodcutter card"
	when
		$player : Player( $username : username )
		$card : Woodcutter (  )
		$action : Action( this == Action.BUY )
	then
		addPurchase($player,1);
		coin($player,2);
		retract($player)
		retract($card)
		retract($action)
end




//WIN RULE
rule "End game rule"
	salience 20
	when
		$situation : Table( situation == 2 )
		$phase : Phase( this == Phase.ENDTURN )
	then
		System.out.println("The game is finished . . .");
		//Sort ascendent the players (the class player implements Comparable)
		Collections.sort(players);
		//Reverse the list
		Collections.reverse(players);
		//Print the ranking
		System.out.println("***RANK***");
		for (int j = 0; j < players.size(); j++)
			System.out.println((j+1)+"-\t"+players.get(j));
end
			